services:
  frontend:
    image: fulib/fulib.org-frontend
    build:
      context: frontend/
      args:
        CONFIGURATION: standalone
    ports:
      - '11340:80'
  backend:
    image: fulib/fulib.org-backend
    build:
      context: backend/
      args:
        VERSION: docker
  nats:
    image: nats:2
    restart: unless-stopped
    ports:
      - "4222:4222"
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
volumes:
  database:
