{{- if .Values.backup.authDb.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-auth-db
spec:
  schedule: {{ .Values.backup.authDb.schedule }}
  timeZone: {{ .Values.backup.timeZone }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 12 }}
          hostAliases:
{{ toYaml .Values.backup.hostAliases | indent 12 }}
          containers:
            - name: backup-postgres-s3
              image: {{ .Values.backup.authDb.image }}
              imagePullPolicy: Always
              env:
                # https://github.com/ds-ukassel/backup-postgres-s3?tab=readme-ov-file#configuration
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ default .Values.authDb.secret.existingSecret "auth-db-secret" }}
                      key: POSTGRES_HOST
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ default .Values.authDb.secret.existingSecret "auth-db-secret" }}
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ default .Values.authDb.secret.existingSecret "auth-db-secret" }}
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ default .Values.authDb.secret.existingSecret "auth-db-secret" }}
                      key: POSTGRES_DATABASE
                - name: MINIO_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.authDb.existingSecret }}
                      key: MINIO_ENDPOINT
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.authDb.existingSecret }}
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.authDb.existingSecret }}
                      key: MINIO_SECRET_KEY
                - name: MINIO_BUCKET
                  value: {{ .Values.backup.authDb.bucket | quote }}
                - name: MINIO_PATH
                  value: {{ .Values.backup.authDb.path | quote }}
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.authDb.existingSecret }}
                      key: DISCORD_WEBHOOK_URL
                      optional: true
                - name: RETENTION_PERIOD
                  value: {{ .Values.backup.authDb.keep | quote }}
{{- end }}
