apiVersion: v2
name: fulib.org
description: A Helm chart for deploying MongoDB, Keycloak, Backend, Frontend, Ingress, and CronJobs
version: 0.1.0
dependencies:
  - name: nats # https://github.com/nats-io/k8s/tree/main/helm/charts/nats
    version: 1.3.2
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
